DROP DATABASE IF EXISTS web_hw;
CREATE DATABASE web_hw DEFAULT CHARSET utf8;

USE web_hw;
CREATE TABLE users(
    id INT UNSIGNED AUTO_INCREMENT,
    email VARCHAR(320) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    token VARCHAR(100),
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
